Repository AY2122S1-CS2103T-F13-1/tp, pull requests merged in 2021-10, with the labels that each got.

#113 Add create and delete group functionality
  build.gradle
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateGroupParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/exceptions/EmptyGroupException.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: priority.HIGH

#123 Update portfolio for marcuspeh
  docs/team/marcuspeh.md
Labels: documentation

#126 Fix code quality issues
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CreateGroupParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: hacktoberfest-accepted

#121 Redesign UI update
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListContactsCommand.java
  src/main/java/seedu/address/logic/commands/ListGroupsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/GroupViewButton.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NavigationButtonPanel.java
  src/main/java/seedu/address/ui/PersonViewButton.java
  src/main/java/seedu/address/ui/UiView.java
  src/main/java/seedu/address/ui/ViewPanel.java
  src/main/java/seedu/address/ui/group/GroupCard.java
  src/main/java/seedu/address/ui/group/GroupListPanel.java
  src/main/java/seedu/address/ui/listener/GroupButtonListener.java
  src/main/java/seedu/address/ui/listener/PersonButtonListener.java
  src/main/java/seedu/address/ui/person/PersonCard.java
  src/main/java/seedu/address/ui/person/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GroupListCard.fxml
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/GroupViewButton.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NavigationButtonPanel.fxml
  src/main/resources/view/PersonViewButton.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ViewPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.HIGH, hacktoberfest-accepted

#135 Add ability to add expenses
  src/main/java/seedu/awe/logic/commands/AddExpenseCommand.java
  src/main/java/seedu/awe/logic/parser/AddExpenseCommandParser.java
  src/main/java/seedu/awe/logic/parser/AddressBookParser.java
  src/main/java/seedu/awe/logic/parser/CliSyntax.java
  src/main/java/seedu/awe/logic/parser/ParserUtil.java
  src/main/java/seedu/awe/model/AddressBook.java
  src/main/java/seedu/awe/model/Model.java
  src/main/java/seedu/awe/model/ModelManager.java
  src/main/java/seedu/awe/model/expense/Cost.java
  src/main/java/seedu/awe/model/expense/Description.java
  src/main/java/seedu/awe/model/expense/Expense.java
  src/main/java/seedu/awe/model/group/Group.java
  src/main/java/seedu/awe/storage/JsonAdaptedExpense.java
  src/main/java/seedu/awe/storage/JsonAdaptedGroup.java
  src/test/java/seedu/awe/logic/commands/AddCommandTest.java
  src/test/java/seedu/awe/logic/commands/CreateGroupCommandTest.java
  src/test/java/seedu/awe/storage/JsonAdaptedGroupTest.java
Labels: priority.HIGH

#155 Add in user stories
  docs/DeveloperGuide.md
Labels: documentation

#167 Edit user guide to reflect mandatory parameters
  docs/UserGuide.md
Labels: documentation, priority.HIGH

#201 Add group add/remove tag functionality
  src/main/java/seedu/awe/logic/commands/GroupAddTagCommand.java
  src/main/java/seedu/awe/logic/commands/GroupRemoveTagCommand.java
  src/main/java/seedu/awe/logic/parser/AddressBookParser.java
  src/main/java/seedu/awe/logic/parser/GroupAddContactCommandParser.java
  src/main/java/seedu/awe/logic/parser/GroupAddTagCommandParser.java
  src/main/java/seedu/awe/logic/parser/GroupRemoveTagCommandParser.java
  src/main/java/seedu/awe/model/tag/Tag.java
Labels: priority.MEDIUM

#219 Update developer guide
  FindGroupsSequenceDiagram.png
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FindGroupsSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState4.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState4.png
Labels: documentation
